# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffh < Formula
  desc "Human-readable time differences (port of Carbon diffForHumans)"
  homepage "https://github.com/wilmanbarrios/wdxtools"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.0/diffh_0.3.0_darwin_amd64.tar.gz"
      sha256 "fc8f0b0a68e9786e78df6d0872a6e95e68ba5b0d4f5320e9f1be3134ce9b71bc"

      define_method(:install) do
        bin.install "diffh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.0/diffh_0.3.0_darwin_arm64.tar.gz"
      sha256 "a9ee062da9886e6667eba60618e47010eb746fffb0e302a72096f7a0a8408f2c"

      define_method(:install) do
        bin.install "diffh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.0/diffh_0.3.0_linux_amd64.tar.gz"
      sha256 "a66e39e17a61db17df1fcd2f69547a287d503a6ab0b4d66b386ffa07c58e0be5"
      define_method(:install) do
        bin.install "diffh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.0/diffh_0.3.0_linux_arm64.tar.gz"
      sha256 "5030ad6dfd9b78e0d7eacf898060549f19a1ef7b0eb74e2ee5b1dac718600604"
      define_method(:install) do
        bin.install "diffh"
      end
    end
  end

  test do
    assert_match "ago", shell_output("#{bin}/diffh 2000-01-01").strip
  end
end
