# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffh < Formula
  desc "Human-readable time differences (port of Carbon diffForHumans)"
  homepage "https://github.com/wilmanbarrios/wdxtools"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.2.0/diffh_0.2.0_darwin_amd64.tar.gz"
      sha256 "a0061e5dfdf1ac7e8083fd109702f84ac9acbe3c99dca5deeb6e7f540671ea27"

      define_method(:install) do
        bin.install "diffh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.2.0/diffh_0.2.0_darwin_arm64.tar.gz"
      sha256 "2ed657183c213f0f94a8b5bb7609bf4be18d708bfce9edcf38067dfd07c1d13e"

      define_method(:install) do
        bin.install "diffh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.2.0/diffh_0.2.0_linux_amd64.tar.gz"
      sha256 "c6eb411d24fd689e8988a298ea0730b03804c11e83508b01eb4ce610f70270da"
      define_method(:install) do
        bin.install "diffh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.2.0/diffh_0.2.0_linux_arm64.tar.gz"
      sha256 "7b02b81a518e09955af3cbdebdc85f6d33a6949534bc5c15e29cd59b08e78d2d"
      define_method(:install) do
        bin.install "diffh"
      end
    end
  end

  test do
    assert_match "ago", shell_output("#{bin}/diffh 2000-01-01").strip
  end
end
