# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Numcrn < Formula
  desc "Abbreviate numbers for humans (port of Laravel Number::abbreviate)"
  homepage "https://github.com/wilmanbarrios/wdxtools"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.2.0/numcrn_0.2.0_darwin_amd64.tar.gz"
      sha256 "26b179d17a74145d0905ca2e9f489c741e3c97d57cca53a7a2bb27be13eae7d1"

      define_method(:install) do
        bin.install "numcrn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.2.0/numcrn_0.2.0_darwin_arm64.tar.gz"
      sha256 "d08c04ba11af776aebbc6d5f0021f6b736d9a98f7459223985beb0bb1024b86d"

      define_method(:install) do
        bin.install "numcrn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.2.0/numcrn_0.2.0_linux_amd64.tar.gz"
      sha256 "cc6bed5e10d9b132750f8f20dc292459289161dd30f00a79a551618c83be019e"
      define_method(:install) do
        bin.install "numcrn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.2.0/numcrn_0.2.0_linux_arm64.tar.gz"
      sha256 "1c65e841860dde5d4a4737d26ed55414a48ba8c3cd726424cc1d4aed3262a0c0"
      define_method(:install) do
        bin.install "numcrn"
      end
    end
  end

  test do
    assert_equal "1K", shell_output("#{bin}/numcrn 1000").strip
  end
end
