# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Numcrn < Formula
  desc "Abbreviate numbers for humans (port of Laravel Number::abbreviate)"
  homepage "https://github.com/wilmanbarrios/wdxtools"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.0/numcrn_0.3.0_darwin_amd64.tar.gz"
      sha256 "59c901538d73f50c6b7f75c89cc920955be55683f50b28e4cc6fbe1b3d93f528"

      define_method(:install) do
        bin.install "numcrn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.0/numcrn_0.3.0_darwin_arm64.tar.gz"
      sha256 "afbc07a4a3c44f12df142979be270badc156d94388ab42cf9748356913d81ef4"

      define_method(:install) do
        bin.install "numcrn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.0/numcrn_0.3.0_linux_amd64.tar.gz"
      sha256 "90aaaaad35871e2b70a56bf3011cc24b844be8091a16bb306805047768bcdcca"
      define_method(:install) do
        bin.install "numcrn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.0/numcrn_0.3.0_linux_arm64.tar.gz"
      sha256 "ff1314a5f2ada7af0c134039a4e7127661c52afd6702231939a465369a8a6539"
      define_method(:install) do
        bin.install "numcrn"
      end
    end
  end

  test do
    assert_equal "1K", shell_output("#{bin}/numcrn 1000").strip
  end
end
