# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wdxtools < Formula
  desc "Everyday formatting tools for the command line"
  homepage "https://github.com/wilmanbarrios/wdxtools"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.2/wdxtools_0.3.2_darwin_amd64.tar.gz"
      sha256 "461655998fb082c2882af7c3d97ff9ea37e46abd0c426bcf04ff7bda4aeb1437"

      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.2/wdxtools_0.3.2_darwin_arm64.tar.gz"
      sha256 "e8fba08406151c8109a1deef7bf2f21fd875997bfd0a7b731823bfd91d0bb006"

      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.2/wdxtools_0.3.2_linux_amd64.tar.gz"
      sha256 "c4d9c43b937819e688ea2344c0f989fe35f4ef6b33b6a46271fc6edc7c7e3225"
      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.2/wdxtools_0.3.2_linux_arm64.tar.gz"
      sha256 "bcaf55380b351798942c3918ab937a858168045d47f92796c13cb293fd5b2e8f"
      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
  end

  test do
    assert_match "ago", shell_output("#{bin}/wdxtools diffh 2000-01-01").strip
    assert_equal "1K", shell_output("#{bin}/wdxtools numcrn 1000").strip
  end
end
