# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wdxtools < Formula
  desc "Everyday formatting tools for the command line"
  homepage "https://github.com/wilmanbarrios/wdxtools"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.3/wdxtools_0.3.3_darwin_amd64.tar.gz"
      sha256 "0c899e7f6728c748854ba2bf4d975205589c472f5885e3dfa900dd7a854745f8"

      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.3/wdxtools_0.3.3_darwin_arm64.tar.gz"
      sha256 "050f8771267860477905104d5c00f639bd9c15a31a572555db08597bf06ea6bb"

      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.3/wdxtools_0.3.3_linux_amd64.tar.gz"
      sha256 "ec5fec9b52bfbdb8fb0d1bbc417ffd487306a2d21f389b594323781029aa7adc"
      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.3/wdxtools_0.3.3_linux_arm64.tar.gz"
      sha256 "5f9334c01be6e7cd6a21b3b304284c49b9c05503a6511d44a16a9a4922e0f3eb"
      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
  end

  test do
    assert_match "ago", shell_output("#{bin}/wdxtools diffh 2000-01-01").strip
    assert_equal "1K", shell_output("#{bin}/wdxtools numcrn 1000").strip
  end
end
