# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wdxtools < Formula
  desc "Everyday formatting tools for the command line"
  homepage "https://github.com/wilmanbarrios/wdxtools"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.4/wdxtools_0.3.4_darwin_amd64.tar.gz"
      sha256 "1a9981d349f14c1c0e0f8cc4f2c98be66cb7f6e46e9085b720974a430ee4c4f8"

      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.4/wdxtools_0.3.4_darwin_arm64.tar.gz"
      sha256 "081bee32e777446ea5581c88edcc2c831a98fb45502fc64d4d841542e774a617"

      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.4/wdxtools_0.3.4_linux_amd64.tar.gz"
      sha256 "b8c60569fbd4b2ba702b07e325f3aada858ceacbaa115dc38ae66f02d667a829"
      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wilmanbarrios/wdxtools/releases/download/v0.3.4/wdxtools_0.3.4_linux_arm64.tar.gz"
      sha256 "53a3e95d37caf7b23df00fa082be4a2f4d1c8ff74b759e7937f39ff87e69f847"
      define_method(:install) do
        bin.install "wdxtools"
        bin.install_symlink "wdxtools" => "diffh"
        bin.install_symlink "wdxtools" => "numcrn"
      end
    end
  end

  test do
    assert_match "ago", shell_output("#{bin}/wdxtools diffh 2000-01-01").strip
    assert_equal "1K", shell_output("#{bin}/wdxtools numcrn 1000").strip
  end
end
